# Generated by Django 6.0.3 on 2026-08-11 09:25

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_title",
                    models.CharField(max_length=200, verbose_name="Email Subject"),
                ),
                ("email_content", models.TextField(verbose_name="Email Body Text")),
                (
                    "fake_link",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Phishing Fake URL"
                    ),
                ),
                (
                    "email_label",
                    models.CharField(
                        choices=[
                            ("legit", "Legitimate Email"),
                            ("phish", "Phishing Email"),
                        ],
                        max_length=10,
                        verbose_name="Email label",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("hr", "HR"), ("finance", "Finance"), ("it", "IT")],
                        max_length=20,
                        verbose_name="Target Department",
                    ),
                ),
                (
                    "fraud_feature_description",
                    models.TextField(
                        blank=True, verbose_name="Deceptive scam features"
                    ),
                ),
                (
                    "risk_keywords",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Risk Keywords (split by comma)",
                    ),
                ),
                (
                    "template_serial",
                    models.IntegerField(
                        choices=[
                            (1, "Template No.1"),
                            (2, "Template No.2"),
                            (3, "Template No.3"),
                            (4, "Template No.4"),
                            (5, "Template No.5"),
                        ],
                        default=1,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Pre-Test Email Template",
                "verbose_name_plural": "Pre-Test Email Templates",
            },
        ),
        migrations.CreateModel(
            name="Level2EmailTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Created by Administrator"),
                            ("user_submit", "Submitted by L3 User"),
                        ],
                        default="admin",
                        max_length=20,
                        verbose_name="Source of Template",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=False, verbose_name="Available for Training"
                    ),
                ),
                ("sender", models.CharField(max_length=256)),
                ("subject", models.CharField(max_length=256)),
                ("content_1", models.TextField(blank=True, null=True)),
                (
                    "link_text_1",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("url_1", models.CharField(blank=True, max_length=512, null=True)),
                ("content_2", models.TextField(blank=True, null=True)),
                (
                    "link_text_2",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("url_2", models.CharField(blank=True, max_length=512, null=True)),
                ("content_3", models.TextField(blank=True, null=True)),
                (
                    "link_text_3",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("url_3", models.CharField(blank=True, max_length=512, null=True)),
                ("content_4", models.TextField(blank=True, null=True)),
                (
                    "link_text_4",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("url_4", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "difficulty_level",
                    models.IntegerField(
                        choices=[
                            (2, "Level 2 Intermediate"),
                            (3, "Level 3 Advanced"),
                            (4, "T0 Baseline Pre‑Test"),
                            (5, "T1 Post‑Training Result Test"),
                        ],
                        verbose_name="Training Difficulty",
                    ),
                ),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("L2_1", "L2 Template 1"),
                            ("L2_2", "L2 Template 2"),
                            ("L2_3", "L2 Template 3"),
                            ("L3_1", "L3 Template 1"),
                            ("L3_2", "L3 Template 2"),
                        ],
                        help_text="Select corresponding template html file",
                        max_length=20,
                        verbose_name="Template File",
                    ),
                ),
                (
                    "email_label",
                    models.CharField(
                        choices=[
                            ("legit", "Legitimate Email"),
                            ("phish", "Phishing Email"),
                        ],
                        max_length=10,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[("hr", "HR"), ("finance", "Finance"), ("it", "IT")],
                        max_length=50,
                        verbose_name="Target Department",
                    ),
                ),
                (
                    "scam_keywords",
                    models.TextField(
                        blank=True, verbose_name="Scam Keywords (comma separated)"
                    ),
                ),
                (
                    "analysis_description",
                    models.TextField(verbose_name="Feedback Analysis Text"),
                ),
            ],
            options={
                "verbose_name": "L2/L3 Training Email Template",
                "verbose_name_plural": "L2/L3 Training Email Templates",
            },
        ),
        migrations.CreateModel(
            name="UserConsentRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=150, verbose_name="Participant Username"
                    ),
                ),
                (
                    "consent_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Consent Submit Time"
                    ),
                ),
            ],
            options={
                "verbose_name": "User Informed Consent Record",
                "verbose_name_plural": "User Informed Consent Records",
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("hr", "Human Resources"),
                            ("finance", "Finance Department"),
                            ("it", "IT Department"),
                            ("admin", "Administrator"),
                        ],
                        default="hr",
                        max_length=20,
                        verbose_name="Job Role",
                    ),
                ),
                ("pre_test_score", models.FloatField(default=0.0)),
                ("post_test_score", models.FloatField(default=0.0)),
                ("l2_total_points", models.IntegerField(default=0)),
                (
                    "unlock_l3",
                    models.BooleanField(
                        default=False, verbose_name="Unlock L3 Training"
                    ),
                ),
                (
                    "has_consented",
                    models.BooleanField(
                        default=False, verbose_name="Has signed consent form"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="AdminModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admin_access_key", models.CharField(max_length=100)),
                (
                    "admin_user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExperimentSurvey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submit_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="Submit Time"),
                ),
                (
                    "q1_interface_clear",
                    models.IntegerField(verbose_name="Q1 Interface Clear(1-5)"),
                ),
                (
                    "q2_operation_easy",
                    models.IntegerField(verbose_name="Q2 Easy Operation(1-5)"),
                ),
                (
                    "q3_session_length_ok",
                    models.IntegerField(
                        verbose_name="Q3 Training Length Appropriate(1-5)"
                    ),
                ),
                (
                    "q4_diff_help_improve",
                    models.IntegerField(
                        verbose_name="Q4 Progressive difficulty improves ability(1-5)"
                    ),
                ),
                (
                    "q5_multi_diff_better",
                    models.IntegerField(
                        verbose_name="Q5 Multi-level better than single difficulty(1-5)"
                    ),
                ),
                (
                    "q6_most_help_level",
                    models.CharField(
                        max_length=10, verbose_name="Q6 Most helpful level"
                    ),
                ),
                (
                    "q7_most_suitable_level",
                    models.CharField(
                        max_length=10, verbose_name="Q7 Best daily training level"
                    ),
                ),
                (
                    "q8_level_advantage_text",
                    models.TextField(verbose_name="Q8 Advantages of L1/L2/L3"),
                ),
                (
                    "q9_difficulty_jump_suggest",
                    models.TextField(
                        verbose_name="Q9 Difficulty jump rationality & comment"
                    ),
                ),
                (
                    "q10_dept_email_match",
                    models.IntegerField(
                        verbose_name="Q10 Emails match my department scene(1-5)"
                    ),
                ),
                (
                    "q11_dept_train_useful",
                    models.IntegerField(
                        verbose_name="Q11 Dept training improves recognition(1-5)"
                    ),
                ),
                (
                    "q12_most_deceptive_dept",
                    models.CharField(
                        max_length=10, verbose_name="Q12 Most deceptive dept mail"
                    ),
                ),
                (
                    "q13_prefer_train_mode",
                    models.CharField(
                        max_length=10, verbose_name="Q13 Prefer L1 general / L2 dept"
                    ),
                ),
                (
                    "q14_t0_t1_performance_diff",
                    models.IntegerField(
                        verbose_name="Q14 Obvious score difference T0-T1(1-5)"
                    ),
                ),
                (
                    "q15_test_reality",
                    models.IntegerField(
                        verbose_name="Q15 T0/T1 reflect real ability(1-5)"
                    ),
                ),
                (
                    "q16_optimize_priority",
                    models.CharField(
                        max_length=20, verbose_name="Q16 Most need optimize module"
                    ),
                ),
                (
                    "q17_add_email_scenario",
                    models.TextField(verbose_name="Q17 Hope to add email scenarios"),
                ),
                (
                    "q18_rule_adjust_suggest",
                    models.TextField(
                        verbose_name="Q18 Suggestions on scoring/unlock rules"
                    ),
                ),
                (
                    "q19_willing_reuse",
                    models.IntegerField(
                        verbose_name="Q19 Will to reuse this system(1-5)"
                    ),
                ),
                (
                    "q20_other_comments",
                    models.TextField(
                        blank=True, null=True, verbose_name="Q20 Extra comments"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiment Questionnaire",
                "verbose_name_plural": "Experiment Questionnaires",
            },
        ),
        migrations.CreateModel(
            name="PreTestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge_result",
                    models.CharField(
                        choices=[
                            ("right", "Correct judgment"),
                            ("wrong", "Wrong judgment"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("operation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("scam_type_tag", models.CharField(blank=True, max_length=50)),
                (
                    "target_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.emailtemplatemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RoleChangeApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("hr", "Human Resources"),
                            ("finance", "Finance Department"),
                            ("it", "IT Department"),
                            ("admin", "Administrator"),
                        ],
                        max_length=20,
                        verbose_name="Want to change to role",
                    ),
                ),
                ("apply_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_remark",
                    models.TextField(blank=True, verbose_name="Admin audit remark"),
                ),
                (
                    "audit_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_applies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (2, "Level 2 Intermediate Training"),
                            (3, "Level 3 Advanced Training"),
                            (4, "T0 Baseline Pre‑Test"),
                            (5, "T1 Post‑Training Result Test"),
                        ]
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.IntegerField(default=0)),
                (
                    "correct_identify",
                    models.IntegerField(default=0, verbose_name="正确辨别钓鱼邮件数"),
                ),
                (
                    "wrong_identify",
                    models.IntegerField(default=0, verbose_name="误举报正常邮件数"),
                ),
                (
                    "pass_level2",
                    models.BooleanField(
                        default=False, verbose_name="是否通过L2，解锁L3"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserEmailAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reject_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reject Reason"
                    ),
                ),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                ("audit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "score_dept_match",
                    models.FloatField(
                        default=0, verbose_name="Department Matching Score(0-30)"
                    ),
                ),
                (
                    "score_social_engineer",
                    models.FloatField(
                        default=0, verbose_name="Social Engineering Score(0-30)"
                    ),
                ),
                (
                    "score_fake_tech",
                    models.FloatField(
                        default=0, verbose_name="Forgery Tech Score(0-25)"
                    ),
                ),
                (
                    "score_flaw",
                    models.FloatField(
                        default=0, verbose_name="Flaw Conceal Score(0-15)"
                    ),
                ),
                (
                    "total_score",
                    models.FloatField(default=0, verbose_name="Total Score"),
                ),
                (
                    "level_grade",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Evaluation Grade"
                    ),
                ),
                (
                    "score_suggest",
                    models.TextField(
                        blank=True, verbose_name="Optimization Suggestions"
                    ),
                ),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_audit_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_submits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_record",
                        to="game.level2emailtemplatemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Submitted Email Audit",
                "verbose_name_plural": "User Submitted Email Audits",
                "ordering": ["-submit_time"],
            },
        ),
        migrations.CreateModel(
            name="UserMailAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("open_mail", "Open mail"),
                            ("mark_suspicious", "Mark as suspicious phishing"),
                            ("delete_mail", "Delete mail"),
                            ("click_link", "Click link inside mail"),
                            ("report_phish", "Report phishing"),
                            ("mark_legit", "Mark as legitimate mail"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                (
                    "confidence",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Judgment Confidence(1~5)",
                    ),
                ),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.level2emailtemplatemodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.trainsession",
                    ),
                ),
            ],
        ),
    ]
