# Generated by Django 6.0.3 on 2026-08-12 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userconsentrecord",
            name="username",
        ),
        migrations.AddField(
            model_name="userconsentrecord",
            name="participant_anon_id",
            field=models.CharField(
                default=1, max_length=64, verbose_name="Anonymous Participant ID"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="usermodel",
            name="anon_participant_id",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                verbose_name="Anonymous Participant ID (Research Only)",
            ),
        ),
    ]
