# Generated by Django 6.0.3 on 2026-07-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplatemodel",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1 Basic"),
                    (2, "Level 2 Intermediate"),
                    (3, "Level 3 Advanced"),
                ],
                default=1,
            ),
        ),
    ]
