# Generated by Django 6.0.3 on 2026-07-20 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_emailtemplatemodel_difficulty_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplatemodel",
            name="fake_link",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Phishing Fake URL"
            ),
        ),
        migrations.AlterField(
            model_name="emailtemplatemodel",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[
                    (1, "Level 1 Basic"),
                    (2, "Level 2 Intermediate"),
                    (3, "Level 3 Advanced"),
                ],
                default=1,
                verbose_name="Difficulty Level",
            ),
        ),
    ]
