# Generated by Django 6.0.3 on 2026-08-12 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0002_remove_userconsentrecord_username_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="experimentsurvey",
            name="q12_most_deceptive_dept",
            field=models.TextField(
                blank=True, null=True, verbose_name="Q12 Most like mail interface"
            ),
        ),
    ]
