# Generated by Django 6.0.3 on 2026-07-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_emailtemplatemodel_fake_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplatemodel",
            name="risk_keywords",
            field=models.CharField(
                blank=True,
                max_length=500,
                verbose_name="Risk Keywords (split by comma)",
            ),
        ),
    ]
