# Generated by Django 6.0.3 on 2026-08-13 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0003_alter_experimentsurvey_q12_most_deceptive_dept"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplatemodel",
            options={
                "verbose_name": "L1 / T0 / T1 Email Template",
                "verbose_name_plural": "L1 / T0 / T1 Email Templates",
            },
        ),
        migrations.AddField(
            model_name="emailtemplatemodel",
            name="test_difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "L1 Basic General Training"),
                    (4, "T0 Baseline Pre-Test"),
                    (5, "T1 Post-Training Test"),
                ],
                default=1,
                verbose_name="Test Stage (L1/T0/T1)",
            ),
        ),
        migrations.AddField(
            model_name="pretestrecord",
            name="test_difficulty",
            field=models.IntegerField(
                choices=[
                    (1, "L1 Basic General Training"),
                    (4, "T0 Baseline Pre-Test"),
                    (5, "T1 Post-Training Test"),
                ],
                default=1,
            ),
        ),
    ]
