# Generated by Django 6.0.3 on 2026-08-13 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_alter_emailtemplatemodel_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DomainWhitelistModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Trusted domain name"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Domain usage description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Trusted Domain Whitelist",
                "verbose_name_plural": "Trusted Domain Whitelist",
                "ordering": ["domain"],
            },
        ),
    ]
