# Generated by Django 6.0.3 on 2026-07-21 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0004_emailtemplatemodel_risk_keywords"),
    ]

    operations = [
        migrations.CreateModel(
            name="RoleChangeApply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "target_role",
                    models.CharField(
                        choices=[
                            ("hr", "Human Resources"),
                            ("finance", "Finance Department"),
                            ("it", "IT Department"),
                        ],
                        max_length=20,
                        verbose_name="Want to change to role",
                    ),
                ),
                ("apply_time", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "admin_remark",
                    models.TextField(blank=True, verbose_name="Admin audit remark"),
                ),
                (
                    "audit_admin",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_applies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
