# Generated by Django 6.0.3 on 2026-07-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_rolechangeapply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolechangeapply",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("hr", "Human Resources"),
                    ("finance", "Finance Department"),
                    ("it", "IT Department"),
                    ("admin", "Administrator"),
                ],
                max_length=20,
                verbose_name="Want to change to role",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "Human Resources"),
                    ("finance", "Finance Department"),
                    ("it", "IT Department"),
                    ("admin", "Administrator"),
                ],
                default="hr",
                max_length=20,
                verbose_name="Job Role",
            ),
        ),
    ]
