# Generated by Django 6.0.3 on 2026-08-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0005_domainwhitelistmodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigRuleModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("dept_hr", "Key words of HR business"),
                            ("dept_finance", "Finance Business Keywords"),
                            ("dept_it", "IT Business Keywords"),
                            ("se_authority", "Social Engineering - Authority"),
                            ("se_urgent", "Social Engineering - Urgency"),
                            ("se_fear", "Social Engineering - Loss/Fear"),
                            ("se_benefit", "Social Engineering - Benefits/Incentives"),
                            ("regex_sender", "Forged Sender Regex"),
                            ("regex_domain", "Forged Domain Regex"),
                            ("flaw_word", "Low-level Scoring Phrases"),
                            ("forbid_word", "Global Prohibited Words"),
                        ],
                        max_length=30,
                        verbose_name="Rule classification",
                    ),
                ),
                (
                    "content",
                    models.CharField(
                        max_length=500, verbose_name="Key words/Regular content"
                    ),
                ),
                (
                    "desc",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Notes and explanations",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notes and explanations",
                "verbose_name_plural": "Notes and explanations",
                "ordering": ["rule_type"],
            },
        ),
    ]
