# Generated by Django 6.0.3 on 2026-08-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_configrulemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("dept_hr", "Key words of HR business"),
                    ("dept_finance", "Finance Business Keywords"),
                    ("dept_it", "IT Business Keywords"),
                    ("se_authority", "Social Engineering - Authority"),
                    ("se_urgent", "Social Engineering - Urgency"),
                    ("se_fear", "Social Engineering - Loss/Fear"),
                    ("se_benefit", "Social Engineering - Benefits/Incentives"),
                    ("regex_sender", "Forged Sender Regex"),
                    ("regex_domain", "Forged Domain Regex"),
                    ("flaw_word", "Low‑level Scoring Phrases"),
                    ("forbid_word", "Global Prohibited Words"),
                ],
                max_length=30,
                verbose_name="Rule classification",
            ),
        ),
    ]
