# Generated by Django 6.0.3 on 2026-07-21 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0006_alter_rolechangeapply_target_role_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplatemodel",
            options={
                "verbose_name": "Training Email Template",
                "verbose_name_plural": "Training Email Templates",
            },
        ),
        migrations.AddField(
            model_name="emailtemplatemodel",
            name="template_serial",
            field=models.IntegerField(
                choices=[
                    (1, "Template No.1"),
                    (2, "Template No.2"),
                    (3, "Template No.3"),
                    (4, "Template No.4"),
                    (5, "Template No.5"),
                ],
                default=1,
                verbose_name="Template Serial No.(1-5, match Lx_x.html)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="emailtemplatemodel",
            name="email_label",
            field=models.CharField(
                choices=[("legit", "Legitimate Email"), ("phish", "Phishing Email")],
                max_length=10,
                verbose_name="Email label",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="emailtemplatemodel",
            unique_together={("department", "difficulty_level", "template_serial")},
        ),
    ]
