# Generated by Django 6.0.3 on 2026-08-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_configrulemodel_rule_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="configrulemodel",
            options={
                "ordering": ["rule_type"],
                "verbose_name": "Scoring Config Rule",
                "verbose_name_plural": "Scoring Config Rules",
            },
        ),
        migrations.AlterField(
            model_name="configrulemodel",
            name="content",
            field=models.CharField(
                max_length=500, verbose_name="Keyword / Regex Content"
            ),
        ),
        migrations.AlterField(
            model_name="configrulemodel",
            name="desc",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Description Remark"
            ),
        ),
        migrations.AlterField(
            model_name="configrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("dept_hr", "HR Business Keywords"),
                    ("dept_finance", "Finance Business Keywords"),
                    ("dept_it", "IT Business Keywords"),
                    ("se_authority", "Social Engineering - Authority"),
                    ("se_urgent", "Social Engineering - Urgent"),
                    ("se_fear", "Social Engineering - Loss Threat"),
                    ("se_benefit", "Social Engineering - Benefit Reward"),
                    ("regex_sender", "Fake Sender Regex Rule"),
                    ("regex_domain", "Fake Domain Regex Rule"),
                    ("flaw_word", "Low-level Obvious Phrase"),
                    ("forbid_word", "Prohibited Sensitive Word"),
                ],
                max_length=30,
                verbose_name="Rule Category",
            ),
        ),
    ]
