# Generated by Django 6.0.3 on 2026-07-21 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0007_alter_emailtemplatemodel_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatemodel",
            name="template_serial",
            field=models.IntegerField(
                choices=[
                    (1, "Template No.1"),
                    (2, "Template No.2"),
                    (3, "Template No.3"),
                    (4, "Template No.4"),
                    (5, "Template No.5"),
                ],
                default=1,
                verbose_name="Template Serial No.(1-5, match Lx_x.html)",
            ),
        ),
    ]
