# Generated by Django 6.0.3 on 2026-07-21 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_emailtemplatemodel_template_serial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="emailtemplatemodel",
            unique_together=set(),
        ),
    ]
