# Generated by Django 6.0.3 on 2026-08-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0008_alter_configrulemodel_options_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DomainWhitelistModel",
        ),
        migrations.AlterField(
            model_name="configrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("dept_hr", "HR Business Keywords"),
                    ("dept_finance", "Finance Business Keywords"),
                    ("dept_it", "IT Business Keywords"),
                    ("se_authority", "Social Engineering - Authority"),
                    ("se_urgent", "Social Engineering - Urgent"),
                    ("se_fear", "Social Engineering - Loss Threat"),
                    ("se_benefit", "Social Engineering - Benefit Reward"),
                    ("regex_sender", "Fake Sender Regex Rule"),
                    ("regex_domain", "Fake Domain Regex Rule"),
                    ("flaw_word", "Low‑level Obvious Phrase"),
                    ("forbid_word", "Prohibited Sensitive Word"),
                    ("trusted_domain", "Trusted Whitelisted Domain"),
                ],
                max_length=30,
                verbose_name="Rule Category",
            ),
        ),
    ]
