# Generated by Django 6.0.3 on 2026-08-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0009_delete_domainwhitelistmodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("dept_hr_legit", "HR Legitimate Business Keywords"),
                    ("dept_hr_phish", "HR Phishing Inducement Keywords"),
                    ("dept_finance_legit", "Finance Legitimate Business Keywords"),
                    ("dept_finance_phish", "Finance Phishing Inducement Keywords"),
                    ("dept_it_legit", "IT Legitimate Business Keywords"),
                    ("dept_it_phish", "IT Phishing Inducement Keywords"),
                    ("se_authority", "Social Engineering - Authority"),
                    ("se_urgent", "Social Engineering - Urgent"),
                    ("se_fear", "Social Engineering - Loss Threat"),
                    ("se_benefit", "Social Engineering - Benefit Reward"),
                    ("regex_sender", "Fake Sender Regex Rule"),
                    ("regex_domain", "Fake Domain Keyword"),
                    ("flaw_word", "Low‑level Obvious Phrase"),
                    ("forbid_word", "Prohibited Sensitive Word"),
                    ("trusted_domain", "Trusted Whitelisted Domain"),
                ],
                max_length=30,
                verbose_name="Rule Category",
            ),
        ),
    ]
