# Generated by Django 6.0.3 on 2026-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_configrulemodel_rule_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainsession",
            name="correct_identify",
            field=models.IntegerField(
                default=0,
                verbose_name="Correctly identify the number of phishing emails",
            ),
        ),
        migrations.AlterField(
            model_name="trainsession",
            name="pass_level2",
            field=models.BooleanField(
                default=False, verbose_name="Whether L2 is passed, unlocking L3"
            ),
        ),
        migrations.AlterField(
            model_name="trainsession",
            name="wrong_identify",
            field=models.IntegerField(
                default=0, verbose_name="Wrongly report legitimate emails"
            ),
        ),
    ]
