# Generated by Django 6.0.3 on 2026-07-23 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0010_alter_gamerecordmodel_judge_result"),
    ]

    operations = [
        migrations.CreateModel(
            name="Level2EmailTemplateModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sender", models.CharField(max_length=255, verbose_name="Sender")),
                (
                    "recipient",
                    models.CharField(max_length=255, verbose_name="Recipient"),
                ),
                (
                    "subject",
                    models.CharField(max_length=255, verbose_name="Email Subject"),
                ),
                (
                    "content_1",
                    models.TextField(blank=True, verbose_name="Content Paragraph 1"),
                ),
                (
                    "url_1",
                    models.CharField(blank=True, max_length=300, verbose_name="URL 1"),
                ),
                (
                    "content_2",
                    models.TextField(blank=True, verbose_name="Content Paragraph 2"),
                ),
                (
                    "url_2",
                    models.CharField(blank=True, max_length=300, verbose_name="URL 2"),
                ),
                (
                    "content_3",
                    models.TextField(blank=True, verbose_name="Content Paragraph 3"),
                ),
                (
                    "url_3",
                    models.CharField(blank=True, max_length=300, verbose_name="URL 3"),
                ),
                (
                    "content_4",
                    models.TextField(blank=True, verbose_name="Content Paragraph 4"),
                ),
                (
                    "url_4",
                    models.CharField(blank=True, max_length=300, verbose_name="URL 4"),
                ),
                (
                    "difficulty_level",
                    models.IntegerField(default=2, verbose_name="Difficulty Level"),
                ),
                (
                    "template_type",
                    models.CharField(
                        help_text="L2_1 / L2_2 / L2_3",
                        max_length=20,
                        verbose_name="Template File",
                    ),
                ),
                (
                    "email_label",
                    models.CharField(
                        choices=[("phish", "Phishing"), ("legit", "Legitimate")],
                        max_length=10,
                        verbose_name="Email Type",
                    ),
                ),
                (
                    "department",
                    models.CharField(max_length=50, verbose_name="Target Department"),
                ),
                (
                    "scam_keywords",
                    models.TextField(
                        blank=True, verbose_name="Scam Keywords (comma separated)"
                    ),
                ),
                (
                    "analysis_description",
                    models.TextField(verbose_name="Feedback Analysis Text"),
                ),
            ],
            options={
                "verbose_name": "Level2 Training Template",
                "verbose_name_plural": "Level2 Training Templates",
            },
        ),
        migrations.AlterField(
            model_name="gamerecordmodel",
            name="target_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.emailtemplatemodel",
            ),
        ),
        migrations.AddField(
            model_name="gamerecordmodel",
            name="target_l2_email",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="game.level2emailtemplatemodel",
            ),
        ),
    ]
