# Generated by Django 6.0.3 on 2026-07-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_level2emailtemplatemodel_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="recipient",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Recipient"
            ),
        ),
    ]
