# Generated by Django 6.0.3 on 2026-08-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0011_alter_trainsession_correct_identify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configrulemodel",
            name="rule_type",
            field=models.CharField(
                choices=[
                    ("dept_hr_legit", "HR Legitimate Business Keywords"),
                    ("dept_hr_phish", "HR Phishing Inducement Keywords"),
                    ("dept_finance_legit", "Finance Legitimate Business Keywords"),
                    ("dept_finance_phish", "Finance Phishing Inducement Keywords"),
                    ("dept_it_legit", "IT Legitimate Business Keywords"),
                    ("dept_it_phish", "IT Phishing Inducement Keywords"),
                    (
                        "dept_company_legit",
                        "Company‑Corporate Legitimate Business Keywords",
                    ),
                    (
                        "dept_company_phish",
                        "Company‑Corporate Phishing Inducement Keywords",
                    ),
                    ("se_authority", "Social Engineering - Authority"),
                    ("se_urgent", "Social Engineering - Urgent"),
                    ("se_fear", "Social Engineering - Loss Threat"),
                    ("se_benefit", "Social Engineering - Benefit Reward"),
                    ("regex_sender", "Fake Sender Regex Rule"),
                    ("regex_domain", "Fake Domain Keyword"),
                    ("flaw_word", "Low‑level Obvious Phrase"),
                    ("forbid_word", "Prohibited Sensitive Word"),
                    ("trusted_domain", "Trusted Whitelisted Domain"),
                ],
                max_length=30,
                verbose_name="Rule Category",
            ),
        ),
        migrations.AlterField(
            model_name="rolechangeapply",
            name="target_role",
            field=models.CharField(
                choices=[
                    ("hr", "Human Resources"),
                    ("finance", "Finance Department"),
                    ("it", "IT Department"),
                    ("company", "Company Corporate"),
                    ("admin", "Administrator"),
                ],
                max_length=20,
                verbose_name="Want to change to role",
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="role",
            field=models.CharField(
                choices=[
                    ("hr", "Human Resources"),
                    ("finance", "Finance Department"),
                    ("it", "IT Department"),
                    ("company", "Company Corporate"),
                    ("admin", "Administrator"),
                ],
                default="hr",
                max_length=20,
                verbose_name="Job Role",
            ),
        ),
    ]
