# Generated by Django 6.0.3 on 2026-08-21 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_alter_configrulemodel_rule_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplatemodel",
            name="department",
            field=models.CharField(
                choices=[
                    ("hr", "HR"),
                    ("finance", "Finance"),
                    ("it", "IT"),
                    ("company", "Company Corporate"),
                ],
                max_length=20,
                verbose_name="Target Department",
            ),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="department",
            field=models.CharField(
                choices=[
                    ("hr", "HR"),
                    ("finance", "Finance"),
                    ("it", "IT"),
                    ("company", "Company Corporate"),
                ],
                max_length=50,
                verbose_name="Target Department",
            ),
        ),
    ]
