# Generated by Django 6.0.3 on 2026-07-27 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0012_alter_level2emailtemplatemodel_recipient"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="emailtemplatemodel",
            options={
                "verbose_name": "Pre-Test Email Template",
                "verbose_name_plural": "Pre-Test Email Templates",
            },
        ),
        migrations.AlterModelOptions(
            name="level2emailtemplatemodel",
            options={
                "verbose_name": "L2/L3 Training Email Template",
                "verbose_name_plural": "L2/L3 Training Email Templates",
            },
        ),
        migrations.RemoveField(
            model_name="emailtemplatemodel",
            name="difficulty_level",
        ),
        migrations.AddField(
            model_name="usermodel",
            name="l2_total_points",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usermodel",
            name="unlock_l3",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="emailtemplatemodel",
            name="template_serial",
            field=models.IntegerField(
                choices=[
                    (1, "Template No.1"),
                    (2, "Template No.2"),
                    (3, "Template No.3"),
                    (4, "Template No.4"),
                    (5, "Template No.5"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="department",
            field=models.CharField(
                choices=[("hr", "HR"), ("finance", "Finance"), ("it", "IT")],
                max_length=50,
                verbose_name="Target Department",
            ),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="difficulty_level",
            field=models.IntegerField(
                choices=[(2, "Level 2 Intermediate"), (3, "Level 3 Advanced")],
                verbose_name="Training Difficulty",
            ),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="email_label",
            field=models.CharField(
                choices=[("legit", "Legitimate Email"), ("phish", "Phishing Email")],
                max_length=10,
                verbose_name="Email Type",
            ),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="template_type",
            field=models.CharField(
                help_text="L2_1 / L3_1 ...", max_length=20, verbose_name="Template File"
            ),
        ),
        migrations.CreateModel(
            name="PreTestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judge_result",
                    models.CharField(
                        choices=[
                            ("right", "Correct judgment"),
                            ("wrong", "Wrong judgment"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "confidence_score",
                    models.IntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("operation_timestamp", models.DateTimeField(auto_now_add=True)),
                ("scam_type_tag", models.CharField(blank=True, max_length=50)),
                (
                    "target_email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.emailtemplatemodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "difficulty",
                    models.IntegerField(
                        choices=[
                            (2, "Level 2 Intermediate Training"),
                            (3, "Level 3 Advanced Training"),
                        ]
                    ),
                ),
                ("start_time", models.DateTimeField(auto_now_add=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("total_score", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserMailAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("open_mail", "打开邮件"),
                            ("mark_suspicious", "标记可疑钓鱼"),
                            ("delete_mail", "删除邮件"),
                            ("click_link", "点击邮件内链接"),
                        ],
                        max_length=30,
                    ),
                ),
                ("action_time", models.DateTimeField(auto_now_add=True)),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.level2emailtemplatemodel",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="game.trainsession",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="GameRecordModel",
        ),
    ]
