# Generated by Django 6.0.3 on 2026-08-22 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0013_alter_emailtemplatemodel_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userconsentrecord",
            name="real_name",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                verbose_name="Participant Real Name",
            ),
        ),
    ]
