# Generated by Django 6.0.3 on 2026-08-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_userconsentrecord_real_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="usermailaction",
            name="is_correct",
            field=models.BooleanField(
                blank=True, null=True, verbose_name="Judgment Correct or Not"
            ),
        ),
        migrations.AddField(
            model_name="usermailaction",
            name="score",
            field=models.IntegerField(
                blank=True,
                null=True,
                verbose_name="Single‑action score(negative=penalty)",
            ),
        ),
    ]
