# Generated by Django 6.0.3 on 2026-07-27 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0014_alter_usermailaction_action_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainsession",
            name="correct_identify",
            field=models.IntegerField(default=0, verbose_name="正确辨别钓鱼邮件数"),
        ),
        migrations.AddField(
            model_name="trainsession",
            name="pass_level2",
            field=models.BooleanField(default=False, verbose_name="是否通过L2，解锁L3"),
        ),
        migrations.AddField(
            model_name="trainsession",
            name="wrong_identify",
            field=models.IntegerField(default=0, verbose_name="误举报正常邮件数"),
        ),
    ]
