# Generated by Django 6.0.3 on 2026-07-27 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0015_trainsession_correct_identify_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermailaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("open_mail", "打开邮件"),
                    ("mark_suspicious", "标记可疑钓鱼"),
                    ("delete_mail", "删除邮件"),
                    ("click_link", "点击邮件内链接"),
                    ("report_phish", "举报钓鱼"),
                    ("mark_legit", "判定为正常邮件"),
                ],
                max_length=30,
            ),
        ),
    ]
