# Generated by Django 6.0.3 on 2026-07-27 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0016_alter_usermailaction_action_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermailaction",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("open_mail", "Open mail"),
                    ("mark_suspicious", "Mark as suspicious phishing"),
                    ("delete_mail", "Delete mail"),
                    ("click_link", "Click link inside mail"),
                    ("report_phish", "Report phishing"),
                    ("mark_legit", "Mark as legitimate mail"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="usermodel",
            name="unlock_l3",
            field=models.BooleanField(default=False, verbose_name="Unlock L3 Training"),
        ),
    ]
