# Generated by Django 6.0.3 on 2026-08-01 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0017_alter_usermailaction_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="is_available",
            field=models.BooleanField(
                default=False, verbose_name="Available for Training"
            ),
        ),
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="source",
            field=models.CharField(
                choices=[
                    ("admin", "Created by Administrator"),
                    ("user_submit", "Submitted by L3 User"),
                ],
                default="admin",
                max_length=20,
                verbose_name="Source of Template",
            ),
        ),
        migrations.CreateModel(
            name="UserEmailAudit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "reject_note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Reject Reason"
                    ),
                ),
                ("submit_time", models.DateTimeField(auto_now_add=True)),
                ("audit_time", models.DateTimeField(blank=True, null=True)),
                (
                    "auditor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_audit_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_submits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "email_template",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_record",
                        to="game.level2emailtemplatemodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Submitted Email Audit",
                "verbose_name_plural": "User Submitted Email Audits",
                "ordering": ["-submit_time"],
            },
        ),
    ]
