# Generated by Django 6.0.3 on 2026-08-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0018_level2emailtemplatemodel_is_available_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("L2_1", "L2 Template 1"),
                    ("L2_2", "L2 Template 2"),
                    ("L2_3", "L2 Template 3"),
                    ("L3_1", "L3 Template 1"),
                    ("L3_2", "L3 Template 2"),
                ],
                help_text="Select corresponding template html file",
                max_length=20,
                verbose_name="Template File",
            ),
        ),
    ]
