# Generated by Django 6.0.3 on 2026-08-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0019_alter_level2emailtemplatemodel_template_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="useremailaudit",
            name="level_grade",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Evaluation Grade"
            ),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="score_dept_match",
            field=models.FloatField(
                default=0, verbose_name="Department Matching Score(0-30)"
            ),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="score_fake_tech",
            field=models.FloatField(default=0, verbose_name="Forgery Tech Score(0-25)"),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="score_flaw",
            field=models.FloatField(default=0, verbose_name="Flaw Conceal Score(0-15)"),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="score_social_engineer",
            field=models.FloatField(
                default=0, verbose_name="Social Engineering Score(0-30)"
            ),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="score_suggest",
            field=models.TextField(blank=True, verbose_name="Optimization Suggestions"),
        ),
        migrations.AddField(
            model_name="useremailaudit",
            name="total_score",
            field=models.FloatField(default=0, verbose_name="Total Score"),
        ),
    ]
