# Generated by Django 6.0.3 on 2026-08-05 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("game", "0020_useremailaudit_level_grade_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="level2emailtemplatemodel",
            name="recipient",
        ),
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="link_text_1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="link_text_2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="link_text_3",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="level2emailtemplatemodel",
            name="link_text_4",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="content_1",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="content_2",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="content_3",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="content_4",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="sender",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="subject",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="url_1",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="url_2",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="url_3",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name="level2emailtemplatemodel",
            name="url_4",
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
